CC = $(CROSS)gcc
#CFLAGS = -g -Wall 

LIBS += -lpcre

MPSE_OBJS = acsm2.o acsm.o bnfa.o mpse.o memory.o

MPSE_SO = libmpse.so

all: $(MPSE_SO) test

.c.o:
	$(CC) $(CFLAGS) -fPIC -c $< -o $@

$(MPSE_SO): $(MPSE_OBJS)
	$(CC) $(CFLAGS) -shared -o $@ $^ $(LIBS)

test: test.c mpse.h
	$(CC) $(CFLAGS) -lmpse -lsqlite3 -L. $< -o $@

clean:
	rm *.o *.so test -f

install:
	cp -f *.so $(INSTALL_ROOT)/usr/local/lib/

